### ISSUE TITLE
Not longer working on OpenElec 2.99.5

### ISSUE THREAD

**Issue by CyrilPeponnet** [beenje/plugin.video.m6groupe#1]
Hi this was working fine before, don't know if it's related to openelec or M6 group or XBMC update : 

Hardware : RPi

```
19:33:18 T:2931360864 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
19:33:18 T:2931360864 WARNING: Previous line repeats 1 times.
19:33:18 T:2931360864  NOTICE: [xbmcswift2] Request for "/play/M6/11280176" matches rule for function "play_clip"
19:33:18 T:2931360864  NOTICE: [plugin.video.m6groupe] JSON request: http://static.m6replay.fr/catalog/m6group_web/m6replay/clip/76/01/clip_infos-11280176.json
19:33:20 T:3043721216  NOTICE: COMXPlayer: Opening: rtmpe://groupemsix.fcod.llnwd.net/a2883/e1/mp4:production/regienum/Top-Chef_c11280176_Episode-7.mp4?s=1364236400&e=1364322800&h=e2740e4c44999661d52
9f45be282166b timeout=10
19:33:20 T:3043721216  NOTICE: CXBMCRenderManager::ResetRenderBuffer - using 5 render buffers
19:33:20 T:2797053024  NOTICE: Thread COMXPlayer start, auto delete: false
19:33:20 T:2797053024  NOTICE: Creating InputStream
19:33:20 T:2797053024 WARNING: HandShake: Type mismatch: client sent 6, server answered 9
19:33:21 T:2797053024   ERROR: HandleCtrl: Ignoring SWFVerification request, use --swfVfy!
19:33:21 T:2797053024  NOTICE: Creating Demuxer
19:33:33 T:2797053024   ERROR: RTMP_ReadPacket, failed to read RTMP packet header
19:33:33 T:2797053024 WARNING: could not find codec parameters for rtmpe://groupemsix.fcod.llnwd.net/a2883/e1/mp4:production/regienum/Top-Chef_c11280176_Episode-7.mp4?s=1364236400&e=1364322800&h=e274
0e4c44999661d529f45be282166b timeout=10
19:33:33 T:2797053024   ERROR: OpenDemuxStream - Error creating demuxer
19:33:33 T:2797053024  NOTICE: COMXPlayer::OnExit()
19:33:33 T:2797053024  NOTICE: COMXPlayer::OnExit() deleting input stream
19:33:33 T:3043721216   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.m6groupe/play/M6/11280176]
```

Thanks

**Comment by beenje** [comment]
Unfortunately it looks like more and more videos are only available via HDS (Adobe HTTP Dynamic Streaming).
The rtmp link that I try to guess from the f4m address doesn't work for more and more videos...
I don't have any solution so far.

**Comment by CyrilPeponnet** [comment]
Too bad... But in this case, rollback to old openelec release make it
works. There is something broken.

My opinion is, if they kept the replay on box like freebox we could
continue to guess and find the source file as I have doubt on HDS support
on Linux devices (and all the boxes are running that way).

Le 25 mars 2013 à 21:57, Benjamin Bertrand notifications@github.com a
écrit :

Unfortunately it looks like more and more videos are only available via HDS
(Adobe HTTP Dynamic Streaming).
The rtmp link that I try to guess from the f4m address doesn't work for
more and more videos...
I don't have any solution so far.

—
Reply to this email directly or view it on
GitHubhttps://github.com/beenje/plugin.video.m6groupe/issues/1#issuecomment-15424981
.

**Comment by beenje** [comment]
Addon broken. Won't be fixed due to DRM used.
