### ISSUE TITLE
Using M6 iPhone interface

### ISSUE THREAD

**Issue by audetto** [beenje/plugin.video.m6groupe#2]
Hi,

I realize this plugin is currently broken due to DRM restrictions from M6.

Have you tried to log the activity of the iPhone app?

I can download the video but I need first to run through the iPhone app, go through squid and get the url of the video/mp2t chunks.

I am unable to guess the url from the clip info. Have you tried?

they are something like that

http://lb.cdn.m6web.fr/s/cu/s/m6replay_iphone/iphone/_csa_moinsde12_M3307H11_M3307H11_SID441_MWIFI_3328/_csa_moinsde12_M3307H11_M3307H11_SID441_MWIFI_3328_110813_093659_4.ts

**Comment by beenje** [comment]
Unfortunately, it doesn't help.
The iPhone app decodes the DRM, but logging the activity won't tell us how.
